-- Cleanup Command Table
DELETE FROM command WHERE name = 'dev';
INSERT INTO command VALUES
('dev', 3, 'Syntax: .dev [on/off]\r\n\r\nEnable or Disable in game Dev tag or show current state if on/off not provided.');
DELETE FROM darkcore_string WHERE entry IN (1136,1137, 1138);
INSERT INTO darkcore_string (`entry`,`content_default`) VALUES
(1136, 'Character %s has never been banned!'),
(1137, 'Dev mode is ON'),
(1138, 'Dev mode is OFF');

DELETE FROM command WHERE name LIKE 'reload%';
DELETE FROM command WHERE name IN
('npc addformation','npc additem','npc addmove','npc allowmove','npc changeentry','npc changelevel','npc delitem','npc factionid','npc flag',
'npc setdeathstate','npc setlink','npc setmodel','npc setmovetype','npc setphase','npc spawndist','npc spawntime','npc tempadd','npc unfollow',
'reload trinity_string','channel set public','gobject set phase','gobject tempadd','honor addkill','loadpath','titles setmask','ticket reset');
INSERT INTO command VALUES
('channel set ownership', 3, 'Syntax: .channel set public  $channel $public\r\n\r\nChange password-changing ability for a channel. 1 for possible, 0 for GM only.'),
('npc add formation', 1, 'Syntax: .npc addformation $leader\nAdd selected creature to a leader\'s formation.'),
('npc add item', 2, 'Syntax: .npc additem #itemId <#maxcount><#incrtime><#extendedcost>r\r\n\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.'),
('npc add move', 2, 'Syntax: .npc addmove #creature_guid [#waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.'),
('npc add temp', 2, 'Adds temporary NPC, not saved to database.'),
('npc delete item', 2, 'Syntax: .npc delitem #itemId\r\n\r\nRemove item #itemid from item list of selected vendor.'),
('npc follow stop', 2, 'Syntax: .npc unfollow\r\n\r\nSelected creature (non pet) stop follow you.'),
('npc set allowmove', 3, 'Syntax: .npc allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented.'),
('npc set deathstate', 2, 'Syntax: .npc setdeathstate on/off\r\n\r\nSet default death state (dead/alive) for npc at spawn.'),
('npc set entry', 3, 'Syntax: .npc changeentry $entry\nSwitch selected creature with another entry from creature_template. - New creature.id value not saved to DB.'),
('npc set factionid', 2, 'Syntax: .npc factionid #factionid\r\n\r\nSet the faction of the selected creature to #factionid.'),
('npc set flag', 2, 'Syntax: .npc flag #npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.'),
('npc set link', 2, 'Syntax: .npc setlink $creatureGUID\r\n\r\nLinks respawn of selected creature to the condition that $creatureGUID defined is alive.'),
('npc set model', 2, 'Syntax: .npc setmodel #displayid\r\n\r\nChange the model id of the selected creature to #displayid.'),
('npc set movetype', 2, 'Syntax: .npc setmovetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.'),
('npc set phase', 2, 'Syntax: .npc setphase #phasemask\r\n\r\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable..'),
('npc set spawndist', 2, 'Syntax: .npc spawndist #dist\r\n\r\nAdjust spawndistance of selected creature to dist.'),
('npc set spawntime', 2, 'Syntax: .npc spawntime #time \r\n\r\nAdjust spawntime of selected creature to time.'),
('reload', 1, 'Syntax: .reload $subcommand\nType .reload to see the list of possible subcommands or .help reload $subcommand to see info on subcommands'),
('reload access_requirement', 1, 'Syntax: .reload all\r\n\r\nReload access_requirement table'),
('reload achievement_criteria_data', 1, 'Syntax: .reload all\r\n\r\nReload achievement_criteria_data table'),
('reload achievement_reward', 1, 'Syntax: .reload all\r\n\r\nReload achievement_reward table'),
('reload all', 1, 'Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded.'),
('reload all gossips', 1, 'Syntax: .reload all gossips\nReload gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables.'),
('reload all item', 1, 'Syntax: .reload all item\nReload page_text, item_enchantment_table tables.'),
('reload all locales', 1, 'Syntax: .reload all locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.'),
('reload all loot', 1, 'Syntax: .reload all loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.'),
('reload all npc', 1, 'Syntax: .reload all npc\nReload npc_option, npc_trainer, npc vendor, points of interest tables.'),
('reload all quest', 1, 'Syntax: .reload all quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.'),
('reload all scripts', 1, 'Syntax: .reload all scripts\nReload gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables.'),
('reload all spell', 1, 'Syntax: .reload all spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.'),
('reload areatrigger_involvedrelation', 1, 'Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table.'),
('reload areatrigger_tavern', 1, 'Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table.'),
('reload areatrigger_teleport', 1, 'Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table.'),
('reload auctions', 1, 'Syntax: .reload all\r\n\r\nReload auctions table'),
('reload autobroadcast', 1, 'Syntax: .reload autobroadcast\nReload autobroadcast table.'),
('reload command', 1, 'Syntax: .reload command\nReload command table.'),
('reload conditions', 1, 'Reload conditions table.'),
('reload config', 1, 'Syntax: .reload config\r\n\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.'),
('reload creature_ai_scripts', 1, 'Syntax: .reload all\r\n\r\nReload creature_ai_scripts table'),
('reload creature_ai_summons', 1, 'Syntax: .reload all\r\n\r\nReload creature_ai_summons table'),
('reload creature_ai_texts', 1, 'Syntax: .reload all\r\n\r\nReload creature_ai_texts table'),
('reload creature_involvedrelation', 1, 'Syntax: .reload creature_involvedrelation\nReload creature_involvedrelation table.'),
('reload creature_linked_respawn', 1, 'Syntax: .reload creature_linked_respawn\r\nReload creature_linked_respawn table.'),
('reload creature_loot_template', 1, 'Syntax: .reload creature_loot_template\nReload creature_loot_template table.'),
('reload creature_onkill_reputation', 1, 'Syntax: .reload all\r\n\r\nReload creature_onkill_reputation table'),
('reload creature_questrelation', 1, 'Syntax: .reload creature_questrelation\nReload creature_questrelation table.'),
('reload creature_template', 1, 'Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template.'),
('reload creature_text', 1, 'Syntax: .reload creature_text\r\nReload creature_text table.'),
('reload darkcore_string', 1, 'Syntax: .reload trinity_string\nReload trinity_string table.'),
('reload disables', 1, 'Syntax: .reload disables\r\nReload disables table.'),
('reload disenchant_loot_template', 1, 'Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table.'),
('reload event_scripts', 1, 'Syntax: .reload event_scripts\nReload event_scripts table.'),
('reload fishing_loot_template', 1, 'Syntax: .reload fishing_loot_template\nReload fishing_loot_template table.'),
('reload gameobject_involvedrelation', 1, 'Syntax: .reload gameobject_involvedrelation\nReload gameobject_involvedrelation table.'),
('reload gameobject_loot_template', 1, 'Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table.'),
('reload gameobject_questrelation', 1, 'Syntax: .reload gameobject_questrelation\nReload gameobject_questrelation table.'),
('reload gameobject_scripts', 1, 'Syntax: .reload gameobject_scripts\nReload gameobject_scripts table.'),
('reload game_graveyard_zone', 1, 'Syntax: .reload game_graveyard_zone\nReload game_graveyard_zone table.'),
('reload game_tele', 1, 'Syntax: .reload game_tele\nReload game_tele table.'),
('reload gm_tickets', 1, 'Syntax: .reload gm_tickets\nReload gm_tickets table.'),
('reload gossip_menu', 1, 'Syntax: .reload gossip_menu\nReload gossip_menu table.'),
('reload gossip_menu_option', 1, 'Syntax: .reload gossip_menu_option\nReload gossip_menu_option table.'),
('reload gossip_scripts', 3, 'Syntax: .reload gossip_scripts\nReload gossip_scripts table.'),
('reload item_enchantment_template', 1, 'Syntax: .reload item_enchantment_template\nReload item_enchantment_template table.'),
('reload item_loot_template', 1, 'Syntax: .reload item_loot_template\nReload item_loot_template table.'),
('reload item_set_names', 1, 'Syntax: .reload item_set_names\nReload item_set_names table.'),
('reload lfg_dungeon_rewards', 1, 'Syntax: .reload lfg_dungeon_rewards\nReload lfg_dungeon_rewards table.'),
('reload locales_achievement_reward', 1, 'Syntax: .reload all\r\n\r\nReload locales_achievement_reward table'),
('reload locales_creature', 1, 'Syntax: .reload locales_creature\nReload locales_creature table.'),
('reload locales_gameobject', 1, 'Syntax: .reload locales_gameobject\nReload locales_gameobject table.'),
('reload locales_gossip_menu_option', 1, 'Syntax: .reload locales_gossip_menu_option\nReload locales_gossip_menu_option table.'),
('reload locales_item', 1, 'Syntax: .reload locales_item\nReload locales_item table.'),
('reload locales_item_set_name', 1, 'Syntax: .reload locales_item_set_name\nReload locales_item_set_name table.'),
('reload locales_npc_text', 1, 'Syntax: .reload locales_npc_text\nReload locales_npc_text table.'),
('reload locales_page_text', 1, 'Syntax: .reload locales_page_text\nReload locales_page_text table.'),
('reload locales_points_of_interest', 1, 'Syntax: .reload locales_points_of_interest\nReload locales_point_of_interest table.'),
('reload locales_quest', 1, 'Syntax: .reload locales_quest\nReload locales_quest table.'),
('reload mail_level_reward', 1, 'Syntax: .reload all\r\n\r\nReload mail_level_reward table'),
('reload mail_loot_template', 1, 'Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table.'),
('reload milling_loot_template', 1, 'Syntax: .reload milling_loot_template\nReload milling_loot_template table.'),
('reload npc_spellclick_spells', 1, 'Syntax: .reload all\r\n\r\nReload npc_spellclick_spells table'),
('reload npc_trainer', 1, 'Syntax: .reload npc_trainer\nReload npc_trainer table.'),
('reload npc_vendor', 1, 'Syntax: .reload npc_vendor\nReload npc_vendor table.'),
('reload page_text', 1, 'Syntax: .reload page_text\nReload page_text table.'),
('reload pickpocketing_loot_template', 1, 'Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table.'),
('reload points_of_interest', 1, 'Syntax: .reload points_of_interest\nReload points_of_interest table.'),
('reload prospecting_loot_template', 1, 'Syntax: .reload prospecting_loot_template\nReload prospecting_loot_template table.'),
('reload quest_end_scripts', 1, 'Syntax: .reload quest_end_scripts\nReload quest_end_scripts table.'),
('reload quest_poi', 1, 'Syntax: .reload quest_poi\nReload quest_poi table.'),
('reload quest_start_scripts', 1, 'Syntax: .reload quest_start_scripts\nReload quest_start_scripts table.'),
('reload quest_template', 1, 'Syntax: .reload quest_template\nReload quest_template table.'),
('reload reference_loot_template', 1, 'Syntax: .reload reference_loot_template\nReload reference_loot_template table.'),
('reload reputation_reward_rate', 1, 'Syntax: .reload all\r\n\r\nReload reputation_reward_rate table'),
('reload reputation_spillover_template', 1, 'Syntax: .reload all\r\n\r\nReload reputation_spillover_template table'),
('reload reserved_name', 1, 'Syntax: .reload reserved_name\nReload reserved_name table.'),
('reload skill_discovery_template', 1, 'Syntax: .reload skill_discovery_template\nReload skill_discovery_template table.'),
('reload skill_extra_item_template', 1, 'Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table.'),
('reload skill_fishing_base_level', 1, 'Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table.'),
('reload skinning_loot_template', 1, 'Syntax: .reload skinning_loot_template\nReload skinning_loot_template table.'),
('reload smart_scripts', 3, 'Syntax: .reload smart_scripts\nReload smart_scripts table.'),
('reload spell_area', 1, 'Syntax: .reload spell_area\nReload spell_area table.'),
('reload spell_bonus_data', 1, 'Syntax: .reload spell_bonus_data\nReload spell_bonus_data table.'),
('reload spell_group', 1, 'Syntax: .reload spell_group\nReload spell_group table.'),
('reload spell_group_stack_rules', 1, 'Syntax: .reload spell_group\nReload spell_group_stack_rules table.'),
('reload spell_learn_spell', 1, 'Syntax: .reload spell_learn_spell\nReload spell_learn_spell table.'),
('reload spell_linked_spell', 1, 'Usage: .reload spell_linked_spell\r\nReloads the spell_linked_spell DB table.'),
('reload spell_loot_template', 1, 'Syntax: .reload spell_loot_template\nReload spell_loot_template table.'),
('reload spell_pet_auras', 1, 'Syntax: .reload spell_pet_auras\nReload spell_pet_auras table.'),
('reload spell_proc_event', 1, 'Syntax: .reload spell_proc_event\nReload spell_proc_event table.'),
('reload spell_required', 1, 'Syntax: .reload spell_required\nReload spell_required table.'),
('reload spell_scripts', 1, 'Syntax: .reload spell_scripts\nReload spell_scripts table.'),
('reload spell_target_position', 1, 'Syntax: .reload spell_target_position\nReload spell_target_position table.'),
('reload spell_threats', 1, 'Syntax: .reload spell_threats\nReload spell_threats table.'),
('reload waypoint_scripts', 1, 'Syntax: .reload waypoint_scripts\nReload waypoint_scripts table.');

UPDATE command set name='gobject set phase' WHERE name='gobject setphase';